<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ej91mw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ej91mw/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7ej91mw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7ej91mw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7ej91mw\appProdProjectContainer([
    'container.build_hash' => '7ej91mw',
    'container.build_id' => '2a0344af',
    'container.build_time' => 1605916754,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7ej91mw');
