<?php

namespace Proxies\__CG__\alomedBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pharmacie extends \alomedBundle\Entity\Pharmacie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'id', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'nom', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'prenom', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'adresse', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'livraisons', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'medicaments', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'ordonnanceph', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'password', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'email'];
        }

        return ['__isInitialized__', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'id', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'nom', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'prenom', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'adresse', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'livraisons', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'medicaments', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'ordonnanceph', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'password', '' . "\0" . 'alomedBundle\\Entity\\Pharmacie' . "\0" . 'email'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pharmacie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdonnanceph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdonnanceph', []);

        return parent::getOrdonnanceph();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdonnanceph($ordonnanceph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdonnanceph', [$ordonnanceph]);

        return parent::setOrdonnanceph($ordonnanceph);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivraisons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivraisons', []);

        return parent::getLivraisons();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivraisons($livraisons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivraisons', [$livraisons]);

        return parent::setLivraisons($livraisons);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedicaments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedicaments', []);

        return parent::getMedicaments();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedicaments($medicaments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedicaments', [$medicaments]);

        return parent::setMedicaments($medicaments);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

}
