<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerChmrhnl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerChmrhnl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerChmrhnl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerChmrhnl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerChmrhnl\appDevDebugProjectContainer([
    'container.build_hash' => 'Chmrhnl',
    'container.build_id' => '6f8255e4',
    'container.build_time' => 1608213826,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerChmrhnl');
