<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJk8s8ix\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJk8s8ix/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJk8s8ix.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJk8s8ix\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJk8s8ix\appDevDebugProjectContainer([
    'container.build_hash' => 'Jk8s8ix',
    'container.build_id' => '7724eb59',
    'container.build_time' => 1623623917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJk8s8ix');
